In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("movies_metadata.csv")
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.shape

(45466, 24)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
df = df[['genres','overview','popularity','tagline','title','vote_average']]

In [ ]:
df.head()

,genres,overview,popularity,tagline,title,vote_average
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",21.946943,NaN,Toy Story,7.7
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,Jumanji,6.9
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [ ]:
df.duplicated().sum()

np.int64(13)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

genres              0
overview          954
popularity          5
tagline         25045
title               6
vote_average        6
dtype: int64

In [ ]:
df = df.dropna(subset='title')

In [ ]:
df.isnull().sum()

genres              0
overview          954
popularity          0
tagline         25039
title               0
vote_average        0
dtype: int64

In [ ]:
df[['overview','tagline']] = df[['overview','tagline']].fillna(" ")

In [ ]:
df.isnull().sum()

genres          0
overview        0
popularity      0
tagline         0
title           0
vote_average    0
dtype: int64

In [ ]:
df.head()

,genres,overview,popularity,tagline,title,vote_average
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",21.946943,,Toy Story,7.7
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,Jumanji,6.9
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [ ]:
df['genres'][1]

"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
from ast import literal_eval
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in literal_eval(x)]))

In [ ]:
df.head()

,genres,overview,popularity,tagline,title,vote_average
0,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,,Toy Story,7.7
1,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,Jumanji,6.9
2,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5
3,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,Waiting to Exhale,6.1
4,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7

In [ ]:
df['tags'] = df['overview'] + df['tagline'] + df['genres']

In [ ]:
df.head()

,genres,overview,popularity,tagline,title,vote_average,tags
0,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,,Toy Story,7.7,"Led by Woody, Andy's toys live happily in his ..."
1,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,Jumanji,6.9,When siblings Judy and Peter discover an encha...
2,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,A family wedding reignites the ancient feud be...
3,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,"Cheated on, mistreated and stepped on, the wom..."
4,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.Roll the dice and unleash the excitement!Adventure Fantasy Family"

In [ ]:
import nltk
from nltk import WordNetLemmatizer
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)


  stop_words = set(stopwords.words('english'))
  wrodnet = WordNetLemmatizer()

  words = text.split()
  words = [word for word in words if word not in stop_words]
  words = [wrodnet.lemmatize(word) for word in words]

  return " ".join(words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [ ]:
df['tags'] = df['tags'].apply(preprocess_text)

In [ ]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creaturesroll dice unleash excitementadventure fantasy family'

In [ ]:
df.head()

,genres,overview,popularity,tagline,title,vote_average,tags
0,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",21.946943,,Toy Story,7.7,led woody andys toy live happily room andys bi...
1,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,17.015539,Roll the dice and unleash the excitement!,Jumanji,6.9,sibling judy peter discover enchanted board ga...
2,Romance Comedy,A family wedding reignites the ancient feud be...,11.7129,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,family wedding reignites ancient feud nextdoor...
3,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",3.859495,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,cheated mistreated stepped woman holding breat...
4,Comedy,Just when George Banks has recovered from his ...,8.387519,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,george bank recovered daughter wedding receive...

In [ ]:
df.reset_index(drop=True,inplace=True)

In [ ]:
indacies = pd.Series(df.index,index = df['title'])
indacies

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features = 50000,ngram_range=(1,2),stop_words='english')
tfidf_metrix = vectorizer.fit_transform(df['tags'])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

def reccomedation(title,n = 10):
  if title not in indacies:
    return "Movie not found"
  idx = indacies[title]
  sim_scores = list(enumerate(cosine_similarity(tfidf_metrix[idx],tfidf_metrix)[0]))
  sim_scores = sorted(sim_scores,key = lambda x:x[1],reverse=True)

  sim_scores = sim_scores[1:n+1]
  movie_indices = [i[0] for i in sim_scores]
  return df['title'].iloc[movie_indices]

In [ ]:
reccomedation('Father of the Bride Part II')

43868    George of the Jungle 2
19794                   Babbitt
6305            North to Alaska
6570                      Kuffs
15833          Rhapsody in Blue
32125                 Lambchops
5004                    Wendigo
27962          I Start Counting
34450         You're Killing Me
6792        Father of the Bride
Name: title, dtype: object

In [ ]:
indacies.index[:-1]

Index(['Toy Story', 'Jumanji', 'Grumpier Old Men', 'Waiting to Exhale',
       'Father of the Bride Part II', 'Heat', 'Sabrina', 'Tom and Huck',
       'Sudden Death', 'GoldenEye',
       ...
       'St. Michael Had a Rooster', 'House of Horrors',
       'Shadow of the Blair Witch', 'The Burkittsville 7', 'Caged Heat 3000',
       'Robin Hood', 'Subdue', 'Century of Birthing', 'Betrayal',
       'Satan Triumphant'],
      dtype='object', name='title', length=45446)

In [ ]:
import pickle

pickle.dump(tfidf_metrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indacies,open('indacies.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(vectorizer,open('tfidf.pkl','wb'))